# Generated by Django 5.2.9 on 2026-01-08 23:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('sender', 'Отправитель'), ('transporter', 'Перевозчик'), ('admin', 'Администратор')], default='sender', max_length=15, verbose_name='Тип пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sender_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип отправителя')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя/Название')),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='transporter_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Тип перевозчика')),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя/Название компании')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)')),
                ('height', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Высота (м)')),
                ('width', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Ширина (м)')),
                ('length', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Длина (м)')),
                ('coast', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('address_departure', models.CharField(max_length=100, verbose_name='Адрес отправления')),
                ('address_arrival', models.CharField(max_length=100, verbose_name='Адрес назначения')),
                ('lat_departure', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта отправления')),
                ('lon_departure', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота отправления')),
                ('lat_arrival', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта назначения')),
                ('lon_arrival', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота назначения')),
                ('status', models.CharField(choices=[('searching', 'Поиск перевозчика'), ('assigned', 'Назначен'), ('in_transit', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='searching', max_length=20, verbose_name='Статус')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_departure_plan', models.DateTimeField(verbose_name='Плановая дата отправки')),
                ('date_arrival_plan', models.DateTimeField(verbose_name='Плановая дата доставки')),
                ('date_departure_fact', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата отправки')),
                ('date_arrival_fact', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата доставки')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cargo.sender')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cargo.transporter')),
            ],
            options={
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('truck', 'Грузовик'), ('van', 'Фургон'), ('minivan', 'Минивэн'), ('pickup', 'Пикап')], max_length=25, verbose_name='Тип транспорта')),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Грузоподъемность (кг)')),
                ('length', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Длина кузова (м)')),
                ('width', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Ширина кузова (м)')),
                ('height', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Высота кузова (м)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='cargo.transporter')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Текущая широта')),
                ('current_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Текущая долгота')),
                ('date_departure_plan', models.DateTimeField(verbose_name='Плановая дата отправления по маршруту')),
                ('date_arrival_plan', models.DateTimeField(verbose_name='Плановая дата прибытия по маршруту')),
                ('date_departure_fact', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата отправления')),
                ('date_arrival_fact', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая дата прибытия')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='cargo.order')),
                ('transport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='cargo.transport')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('date_arrival_fact__isnull', True)), fields=('order',), name='unique_active_route_per_order')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст отзыва')),
                ('score', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='cargo.order')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to='cargo.sender')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to='cargo.transporter')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sender', 'transporter', 'order'), name='unique_feedback_per_order')],
            },
        ),
    ]
